Repository DubstepJS/core, pull requests merged in 2018-11, with the labels that each got.

#39 Upgrade dependencies to fix building in a docker container
  .buildkite/pipeline.yml
  .npmrc
  Dockerfile
  README.md
  package.json
  yarn.lock
Labels: bugfix

#44 Use recast for parsing and formatting
  .eslintrc.js
  Dockerfile
  README.md
  package.json
  src/core/index.test.js
  src/utils/ensure-js-imports.test.js
  src/utils/generate-js.js
  src/utils/insert-js-after.js
  src/utils/insert-js-before.js
  src/utils/parse-js.js
  src/utils/read-file.test.js
  src/utils/remove-js-imports.test.js
  src/utils/replace-js.js
  src/utils/visit-js-import.js
  src/utils/visit-js-import.test.js
  src/utils/with-ignore-file.js
  src/utils/with-js-file.js
  src/utils/with-js-files.js
  src/utils/with-js-files.test.js
  src/utils/with-json-file.test.js
  yarn.lock
Labels: feature

#45 Use babylon instead of @babel/parser for jsx support
  package.json
  src/utils/find-files.js
  src/utils/parse-js.js
  src/utils/parse-js.test.js
Labels: bugfix

#46 Update js file APIs to use globs and respect .gitignores
  README.md
  docs/migrations/00046.md
  src/utils/find-files.js
  src/utils/find-files.test.js
  src/utils/with-js-files.js
  src/utils/with-js-files.test.js
Labels: breaking

#48 Upgrade parser
  package.json
  src/utils/parse-js.js
  src/utils/parse-js.test.js
  yarn.lock
Labels: bugfix
