Repository DubstepJS/core, pull requests merged in 2019-01, with the labels that each got.

#54 Add docs and test for exec options
  README.md
  src/utils/exec.test.js
Labels: enhancement, feature

#56 Fix replaceJs almost always returning false
  README.md
  src/utils/replace-js.js
  src/utils/replace-js.test.js
Labels: bugfix

#57 Release v2.0.4
  package.json
Labels: release
